Repository skyra-project/archid-components, pull requests merged in 2022-04, with the labels that each got.

#23 fix: resolved loads of bugs, setup tests, update deps, and general refactors
  jest.config.mjs
  package.json
  packages/http-framework/README.md
  packages/http-framework/package.json
  packages/http-framework/src/lib/Client.ts
  packages/http-framework/src/lib/Registry.ts
  packages/http-framework/src/lib/interactions/chat-input/decorators.ts
  packages/http-framework/src/lib/interactions/chat-input/shared.ts
  packages/http-framework/src/lib/interactions/context-menu/decorators.ts
  packages/http-framework/src/lib/interactions/context-menu/shared.ts
  packages/http-framework/src/lib/interactions/resolvers/ArgumentsOf.ts
  packages/http-framework/src/lib/interactions/resolvers/InteractionOptions.ts
  packages/http-framework/src/lib/interactions/shared/link.ts
  packages/http-framework/src/lib/structures/Command.ts
  packages/http-framework/src/lib/structures/CommandStore.ts
  packages/http-framework/src/lib/structures/MessageComponentHandler.ts
  packages/http-framework/src/lib/structures/MessageComponentHandlerStore.ts
  packages/http-framework/src/lib/utils/normalizeInput.ts
  packages/http-framework/tests/command-register-body-generation.test.ts
  packages/http-framework/tests/resolvers/InteractionOptions.test.ts
  packages/http-framework/tests/util/util.ts
  packages/shared-http-pieces/package.json
  packages/shared-http-pieces/src/commands/donate.ts
  packages/shared-http-pieces/src/commands/invite.ts
  packages/shared-http-pieces/src/commands/statistics.ts
  packages/shared-http-pieces/src/commands/support.ts
  tsconfig.eslint.json
  yarn.lock
Labels: Meta: BugFix, Meta: Cleanup, Meta: Dependencies, Meta: Documentation, Meta: Feature, Meta: Refactor, Meta: Typings, Priority: High, SEM: Major

#24 refactor: change ACIA.focused value to keyof T
  packages/http-framework/src/lib/interactions/resolvers/InteractionOptions.ts
  packages/http-framework/tests/resolvers/InteractionOptions.test.ts
Labels: Meta: Refactor, Priority: High, SEM: Major

#27 chore: remove third-party copyright notice
  packages/http-framework/src/lib/interactions/chat-input/decorators.ts
  packages/http-framework/src/lib/interactions/resolvers/InteractionOptions.ts
  packages/http-framework/src/lib/interactions/resolvers/THIRD_PARTY_LICENSE
Labels: SEM: Patch

#33 fix(interactions): handle empty options
  packages/http-framework/src/lib/interactions/resolvers/InteractionOptions.ts
  packages/http-framework/src/lib/structures/Command.ts
  packages/http-framework/tests/resolvers/InteractionOptions.test.ts
Labels: Bug: Fixed, Priority: High, SEM: Patch

#28 feat: add support for response updating in commands
  packages/http-framework/src/lib/Client.ts
  packages/http-framework/src/lib/interactions/index.ts
  packages/http-framework/src/lib/interactions/utils/util.ts
  packages/http-framework/src/lib/structures/Command.ts
  packages/http-framework/src/lib/structures/CommandStore.ts
Labels: Meta: Feature, Priority: High, SEM: Minor

#34 feat: add modal and file support
  packages/http-framework/src/lib/interactions/index.ts
  packages/http-framework/src/lib/interactions/utils/util.ts
  packages/http-framework/src/lib/structures/Command.ts
Labels: Meta: Feature, Meta: Refactor, SEM: Major

#35 refactor(IH): rename and finish API
  packages/http-framework/src/index.ts
  packages/http-framework/src/lib/Client.ts
  packages/http-framework/src/lib/interactions/utils/util.ts
  packages/http-framework/src/lib/structures/Command.ts
  packages/http-framework/src/lib/structures/InteractionHandler.ts
  packages/http-framework/src/lib/structures/InteractionHandlerStore.ts
  packages/http-framework/src/lib/structures/MessageComponentHandler.ts
  packages/http-framework/src/lib/structures/MessageComponentHandlerStore.ts
Labels: Meta: Feature, Meta: Refactor, SEM: Major

#36 feat: add file support in responses
  packages/http-framework/package.json
  packages/http-framework/src/lib/interactions/index.ts
  packages/http-framework/src/lib/interactions/utils/util.ts
  packages/http-framework/src/lib/structures/Command.ts
  packages/http-framework/src/lib/structures/CommandStore.ts
  packages/http-framework/src/lib/structures/InteractionHandler.ts
  yarn.lock
Labels: Meta: Feature, Meta: Refactor

#37 fix: ensure that `@RestrictGuildIds([])` makes a command global
  packages/http-framework/src/lib/Registry.ts
Labels: Meta: BugFix, Priority: Critical

#38 feat: added i18n packages
  .npm-deprecaterc.yml
  README.md
  lerna.json
  packages/http-framework-i18n/README.md
  packages/http-framework-i18n/package.json
  packages/http-framework-i18n/src/index.ts
  packages/http-framework-i18n/src/lib/registry.ts
  packages/http-framework-i18n/src/lib/types.ts
  packages/http-framework-i18n/src/lib/utils.ts
  packages/http-framework-i18n/src/tsconfig.json
  packages/http-framework-i18n/tsconfig.eslint.json
  packages/i18next-backend/README.md
  packages/i18next-backend/package.json
  packages/i18next-backend/src/index.ts
  packages/i18next-backend/src/tsconfig.json
  packages/i18next-backend/tsconfig.eslint.json
  scripts/clean.mjs
  yarn.lock
Labels: Meta: Feature, Priority: High

#39 feat: added env utilities
  .npm-deprecaterc.yml
  README.md
  lerna.json
  package.json
  packages/env-utilities/README.md
  packages/env-utilities/package.json
  packages/env-utilities/src/index.ts
  packages/env-utilities/src/lib/setup.ts
  packages/env-utilities/src/lib/types.ts
  packages/env-utilities/src/lib/utils.ts
  packages/env-utilities/src/tsconfig.json
  packages/env-utilities/tsconfig.eslint.json
  packages/env-utilities/tsup.config.ts
  scripts/clean.mjs
  yarn.lock
Labels: Meta: Feature

#44 build: switch to git cliff
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarnrc.yml
  lerna.json
  package.json
  packages/env-utilities/CHANGELOG.md
  packages/env-utilities/README.md
  packages/env-utilities/cliff.toml
  packages/env-utilities/package.json
  packages/http-framework-i18n/CHANGELOG.md
  packages/http-framework-i18n/README.md
  packages/http-framework-i18n/cliff.toml
  packages/http-framework-i18n/package.json
  packages/http-framework/CHANGELOG.md
  packages/http-framework/cliff.toml
  packages/http-framework/package.json
  packages/i18next-backend/CHANGELOG.md
  packages/i18next-backend/README.md
  packages/i18next-backend/cliff.toml
  packages/i18next-backend/package.json
  packages/shared-http-pieces/CHANGELOG.md
  packages/shared-http-pieces/cliff.toml
  packages/shared-http-pieces/package.json
  packages/start-banner/CHANGELOG.md
  packages/start-banner/cliff.toml
  packages/start-banner/package.json
  turbo.json
  yarn.lock
Labels: Meta: Documentation, Meta: GitHub, Priority: Medium

#47 docs(start-banner): make README's banner shorter
  packages/start-banner/README.md
Labels: Meta: Documentation, SEM: N/A

#46 refactor(http-framework-i18n): type enhancements
  packages/http-framework-i18n/src/index.ts
  packages/http-framework-i18n/src/lib/types.ts
  packages/http-framework-i18n/src/lib/utils.ts
Labels: Meta: Refactor, SEM: Major

#45 refactor(http-framework): minor enhancements and fixes
  packages/http-framework/src/lib/Client.ts
  packages/http-framework/src/lib/interactions/utils/util.ts
  packages/http-framework/src/lib/structures/Command.ts
  packages/http-framework/src/lib/structures/CommandStore.ts
  packages/http-framework/src/lib/structures/InteractionHandler.ts
Labels: Meta: Refactor, SEM: Patch

#48 fix(env-utilities): do not assign debug to false
  packages/env-utilities/src/lib/setup.ts
  packages/env-utilities/src/lib/utils.ts
Labels: Meta: BugFix, Meta: Refactor, SEM: Minor

#56 fix(hfx-i18n): add static `type` field as required by i18next
  packages/i18next-backend/src/index.ts
Labels: Meta: BugFix

#55 fix: update discordjs dependencies
  packages/http-framework-i18n/package.json
  packages/http-framework/package.json
  packages/http-framework/tests/command-register-body-generation.test.ts
  packages/shared-http-pieces/package.json
  yarn.lock
Labels: Meta: Dependencies

#61 fix: resolved i18n loader bugs
  packages/http-framework-i18n/src/lib/registry.ts
  packages/i18next-backend/src/index.ts
Labels: Meta: BugFix, Priority: Critical

#62 refactor(shared-http-pieces): new `/info` command
  packages/shared-http-pieces/README.md
  packages/shared-http-pieces/package.json
  packages/shared-http-pieces/src/commands/donate.ts
  packages/shared-http-pieces/src/commands/info.ts
  packages/shared-http-pieces/src/commands/invite.ts
  packages/shared-http-pieces/src/commands/statistics.ts
  packages/shared-http-pieces/src/commands/support.ts
  packages/shared-http-pieces/src/index.ts
  packages/shared-http-pieces/src/lib/i18n/LanguageKeys.ts
  packages/shared-http-pieces/src/lib/i18n/LanguageKeys/All.ts
  packages/shared-http-pieces/src/lib/i18n/LanguageKeys/Commands/All.ts
  packages/shared-http-pieces/src/lib/i18n/LanguageKeys/Commands/Shared.ts
  packages/shared-http-pieces/src/lib/i18n/utils.ts
  packages/shared-http-pieces/src/lib/information.ts
  packages/shared-http-pieces/src/locales/en-US/commands/shared.json
  packages/shared-http-pieces/src/locales/es-ES/commands/shared.json
  packages/shared-http-pieces/src/register.ts
  packages/shared-http-pieces/src/tsconfig.json
  yarn.lock
Labels: Meta: Refactor, SEM: Major

#63 fix(shared-http-pieces): resolved several bugs
  packages/shared-http-pieces/README.md
  packages/shared-http-pieces/package.json
  packages/shared-http-pieces/src/commands/info.ts
  packages/shared-http-pieces/src/index.ts
  packages/shared-http-pieces/src/lib/i18n/LanguageKeys.ts
  packages/shared-http-pieces/src/lib/i18n/LanguageKeys/All.ts
  packages/shared-http-pieces/src/lib/i18n/LanguageKeys/Commands/All.ts
  packages/shared-http-pieces/src/lib/information.ts
  packages/shared-http-pieces/src/locales/en-US/commands/shared.json
  packages/shared-http-pieces/src/locales/es-ES/commands/shared.json
  packages/shared-http-pieces/src/register.ts
  packages/shared-http-pieces/src/tsconfig.json
Labels: Meta: BugFix, Priority: Critical
